module.exports = {
  GUILD_ID: "1463207082042986692",
  WELCOME_CHANNEL_ID: "WSTAW_ID_KANALU_POWITAN",
  LOG_CHANNEL_ID: "WSTAW_ID_KANALU_LOGOW",
  VERIFIED_ROLE_ID: "WSTAW_ID_ROLI",
  TICKET_CATEGORY_ID: "WSTAW_ID_KATEGORII_TICKETOW",
  EMBED_COLOR: 0x2b2d31
};
